### PR TITLE
fix: pass through headers on redirect

### LINKED ISSUE #272: Middleware redirect response ignoring headers
The following response works perfectly fine when running locally
```ts
return NextResponse.redirect("some_url", {
  headers: {
    "set-cookie": "random=123",
    "X-Test": "123",
  },
});
```
However, when deployed to AWS none of these headers are returned from cloudfront.

### PR DESCRIPTION
**Pull request by relsunkaev**
resolves #272

### CODE REVIEW

**Review by khuezy — APPROVED** [review]
Thanks! LGTM

@conico974 @fwang 
Do we want to send ALL the headers back? There may be some headers that we want to omit?

File: packages/open-next/src/adapters/routing/matcher.ts [hunk 1]
```diff
@@ -180,6 +180,7 @@ export function handleRedirects(
       type: event.type,
       statusCode: 308,
       headers: {
+        ...event.headers,
```
Comment (conico974) [inline packages/open-next/src/adapters/routing/matcher.ts:183]: Unless i'm missing something, we don't want to pass `event.headers` here.
`handleRedirects` are for `next.config.js` redirects and `event.headers` in this case are request headers, not response headers.

File: packages/open-next/src/adapters/routing/middleware.ts [hunk 2]
```diff
@@ -32,7 +32,7 @@ type MiddlewareOutputEvent = InternalEvent & {
 
 //    if res.end() is return, the parent needs to return and not process next server
 export async function handleMiddleware(
-  internalEvent: InternalEvent,
+  internalEvent: InternalEvent
```
Comment (conico974) [inline packages/open-next/src/adapters/routing/middleware.ts:35]: There is a bunch of changes like that inside your PR.
It might be your local prettier messing with our eslint config. You can run `pnpm run lint:fix` to solve this

**Review by conico974 — CHANGES_REQUESTED** [review]

File: packages/open-next/src/adapters/routing/middleware.ts [hunk 3]
```diff
@@ -98,6 +98,7 @@ export async function handleMiddleware(
       type: internalEvent.type,
       statusCode: res.statusCode,
       headers: {
+        ...res.headers,
```
Comment (conico974) [inline packages/open-next/src/adapters/routing/middleware.ts:101]: `res.headers` is empty at this point, you probably want to use `resHeaders` instead, but you'll need to do it after they've been set here https://github.com/sst/open-next/blob/2014a1b67f09049b0d8b47f47054adebe24c7a77/packages/open-next/src/adapters/routing/middleware.ts#L126-L135

**Review by conico974 — CHANGES_REQUESTED** [review]
I've run the e2e test locally and it failed, did you manage to make it work this way ?

File: packages/open-next/src/adapters/routing/middleware.ts (hunk 3 above)
Comment (khuezy) [reply packages/open-next/src/adapters/routing/middleware.ts:101]: Good catch. I used the responseHeaders and that worked for me

Comment (khuezy) [reply packages/open-next/src/adapters/routing/middleware.ts:101]: @relsunkaev I don't think we should send back all the headers, it will include all the AMZ geo data too... We should just return `result.response.headers.get('set-cookie') ?? ''`

Comment (conico974) [reply packages/open-next/src/adapters/routing/middleware.ts:101]: That's why i think `resHeaders` is fine it's already what you would have get if it wasn't a redirect, we need to allow people to pass the headers they want, maybe they'd want to pass an api key or an auth header

**Comment by khuezy** [comment]
You'll have to deploy your app and run your e2e test against your deployed example apps.
I'll update the docs w/ better instructions... but for now:
1) `cd examples/sst`
2) `npx sst deploy --stage e2e`
3) export the env
```
          export APP_ROUTER_URL=$(jq -r '.["e2e-example-AppRouter"].url' .sst/outputs.json)
          export PAGES_ROUTER_URL=$(jq -r '.["e2e-example-PagesRouter"].url' .sst/outputs.json)
          export APP_PAGES_ROUTER_URL=$(jq -r '.["e2e-example-AppPagesRouter"].url' .sst/outputs.json)
```
4) `cd packages/tests-e2e`
5) Add `test.only` to isolate your test
6) `npm run e2e:dev`

**Comment by conico974** [comment]
> The tests I wrote with the "set-cookie" header passed but I now realize the way I ran them doesn't test anything. How do you run e2e tests on the output built by open next locally?

@relsunkaev you'll need to deploy with sst. 
Inside `examples/sst` run `pnpm sst deploy --stage test`. Make sure that open-next is properly build before running this command.
And then you'll have to run the e2e tests against the deployed examples. 
I have a little script to make things easier that needs to be run under `packages/tests-e2e`: 
```bash
APP_ROUTER_URL="https://xxxxxxxxxx.cloudfront.net"
echo "APP_ROUTER_URL=$APP_ROUTER_URL"
export APP_ROUTER_URL
PAGES_ROUTER_URL="https://xxxxxxxxxx.cloudfront.net"
echo "PAGES_ROUTER_URL=$PAGES_ROUTER_URL"
export PAGES_ROUTER_URL
APP_PAGES_ROUTER_URL="https://xxxxxxxxxx.cloudfront.net"
echo "APP_PAGES_ROUTER_URL=$APP_PAGES_ROUTER_URL"
export APP_PAGES_ROUTER_URL
pnpm run e2e:dev
```
Just replace the x with the deployed value from the sst deployment

**Comment by khuezy** [comment]
Thanks I'll let @conico974 approve then we can merge.

**Review by conico974 — APPROVED** [review]
LGTM
