### PR TITLE
Fix env file not being copied in V3

### LINKED ISSUE #428: Undefined environment variables after upgrade to V3
Hi,

I have just noticed that after the upgrade to V3, environment variables without the `NEXT_PUBLIC` prefix are showing as `undefined`. The environment variables are used in server components, and therefore do not need the prefix. Downgrading to V2 resolved the issue.

Thank you.

### PR DESCRIPTION
**Pull request by conico974**
Fix #428

### CODE REVIEW

File: packages/open-next/src/build/helper.ts [hunk 1]
```diff
@@ -254,3 +254,20 @@ export function copyOpenNextConfig(
...
+  packagePath: string,
+  outputPath: string,
+) {
+  const baseAppPath = path.join(appPath, ".next/standalone", packagePath);
+  const baseOutputPath = path.join(outputPath, packagePath);
+  const envPath = path.join(baseAppPath, ".env");
+  if (fs.existsSync(envPath)) {
+    fs.copyFileSync(envPath, path.join(baseOutputPath, ".env"));
+  }
+  const envProdPath = path.join(baseAppPath, ".env.production");
```
Comment (khuezy) [inline packages/open-next/src/build/helper.ts:269]: would it makes sense to support `.env.staging` or `.env.<arbitary-staging-env>`?

**Review by khuezy — APPROVED** [review]
LGTM, just 1 question.

File: packages/open-next/src/build/helper.ts (hunk 1 above)
Comment (conico974) [reply packages/open-next/src/build/helper.ts:269]: I don't think we should, next don't copy `.env.local` , `.env.development` or `.env.staging` into the standalone output.
Maybe there is some other, but i think we cover much cases here
