### PR TITLE
fix: prevent duplication of location header

### LINKED ISSUE #368: Duplicating location header
I'm using `next-intl`. Server function handles redirect from middleware, but there is an issue that it duplicates `location` header because of case mismatch.

```
"headers": {
    "location": "https://someurl.com/some-path",
    "Location": "https://someurl.com/some-path"
},
```

### PR DESCRIPTION
**Pull request by r34son**
Closes #368

### CODE REVIEW

File: packages/open-next/src/adapters/routing/middleware.ts [hunk 1]
```diff
@@ -123,18 +123,13 @@ export async function handleMiddleware(
   // If the middleware returned a Redirect, we set the `Location` header with
   // the redirected url and end the response.
   if (res.statusCode >= 300 && res.statusCode < 400) {
-    const location = result.response.headers
```
Comment (khuezy) [inline packages/open-next/src/adapters/routing/middleware.ts:126]: iirc, we had to handle this case specifically for middleware `Redirects`. Can you verify that it works with this change?

Comment (r34son) [reply packages/open-next/src/adapters/routing/middleware.ts:126]: Yeah, i`ve tested it by patching 2.3.6 version. Maybe I need to cover this case by some tests? Do you have any contributing docs?

Comment (khuezy) [reply packages/open-next/src/adapters/routing/middleware.ts:126]: I believe we have this covered (middleware redirect test)[https://github.com/sst/open-next/blob/main/packages/tests-e2e/tests/appRouter/middleware.redirect.test.ts]

App: https://github.com/sst/open-next/blob/main/examples/app-router/middleware.ts#L8

File: packages/open-next/src/adapters/routing/middleware.ts [hunk 2]
```diff
@@ -123,18 +123,13 @@ export async function handleMiddleware(
...
-      .get("location")
-      ?.replace("http://localhost:3000", `https://${req.headers.host}`);
+    resHeaders.location = resHeaders.location?.replace("http://localhost:3000", `https://${req.headers.host}`);
```
Comment (conico974) [inline packages/open-next/src/adapters/routing/middleware.ts:126]: Not sure this will work on every case, what if you set the uppercase `Location` headers in the middleware ?

Comment (r34son) [reply packages/open-next/src/adapters/routing/middleware.ts:126]: here i mentioned that it doesn't matter uppercase or lowercase, key will be lowercase always
https://github.com/sst/open-next/issues/368#issuecomment-1964869309
