### PR TITLE
Fix trailing slash

### LINKED ISSUE #260: Trailing slash redirects not working
Hi,

I am getting the following error in CloudWatch when accessing a URL without a trailing slash, showing only `Internal Server Error` on the page. The `trailingSlash` option is enabled in `next.config.js`, so I am expecting the URL to be redirected to the trailing slash version.

```
{
    "errorType": "TypeError",
    "errorMessage": "Expected \"notfile\" to match \"[^\\/#\\?]+?\", but got \"en-gb/test-page\"",
    "stack": [
        "TypeError: Expected \"notfile\" to match \"[^\\/#\\?]+?\", but got \"en-gb/test-page\"",
        "    at file:///var/task/index.mjs:44:200831",
        "    at zm (file:///var/task/index.mjs:54:3634)",
        "    at s9 (file:///var/task/index.mjs:54:3868)",
        "    at uJ (file:///var/task/index.mjs:54:8973)",
        "    at Runtime._J [as handler] (file:///var/task/index.mjs:54:10780)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1147:29)"
    ]
}
```

The error only appears when using Next.js versions above 13.4.12. Version 2.2.1 of open-next is used, along with 2.28.0 of SST.

Thank you.

### PR DESCRIPTION
**Pull request by conico974**
This PR solve issue with `trailingSlash` config in `next.config.js`. Fix #260 

It also solve an issue when people use `rewrites` config in `next.config.js` using array instead of the more complex 
```js
rewrites: () => ({
beforeFiles: [...],
afterFiles: [...],
...
})
```

### CODE REVIEW

File: packages/open-next/src/adapters/routing/matcher.ts [hunk 1]
```diff
@@ -170,7 +171,40 @@ export function handleRedirects(
   event: InternalEvent,
   redirects: RedirectDefinition[],
 ): InternalResult | undefined {
-  const { internalEvent, __rewrite } = handleRewrites(event, redirects);
+  if (
```
Comment (khuezy) [inline packages/open-next/src/adapters/routing/matcher.ts:174]: The return types here are mostly the same except for the `Location`, perhaps we can simplify the code later.

**Review by khuezy — APPROVED** [review]
